# GitLab CI/CD Pipeline for CodeVault PHP/MySQL Application
# This pipeline includes testing, security scanning, deployment, and monitoring

stages:
  - validate
  - test
  - security
  - build
  - deploy
  - monitor

variables:
  # Application settings
  APP_NAME: "codevault"
  PHP_VERSION: "8.1"
  MYSQL_VERSION: "8.0"
  
  # Database settings for testing
  MYSQL_DATABASE: "codevault_test"
  MYSQL_ROOT_PASSWORD: "test_password"
  MYSQL_USER: "test_user"
  MYSQL_PASSWORD: "test_password"

# Cache configuration for faster builds
cache:
  paths:
    - vendor/
    - node_modules/

# ========================================
# VALIDATION STAGE
# ========================================

php_syntax_check:
  stage: validate
  image: php:${PHP_VERSION}-cli
  before_script:
    - apt-get update -qq && apt-get install -y -qq git
  script:
    - echo "🔍 Checking PHP syntax..."
    - find . -name "*.php" -exec php -l {} \;
    - echo "✅ PHP syntax validation completed"
  only:
    - branches
    - merge_requests

code_quality:
  stage: validate
  image: php:${PHP_VERSION}-cli
  before_script:
    - apt-get update -qq && apt-get install -y -qq git curl
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar --version
  script:
    - echo "📊 Running code quality checks..."
    - php -v
    - echo "✅ Code quality checks completed"
  only:
    - branches
    - merge_requests

# ========================================
# TESTING STAGE
# ========================================

unit_tests:
  stage: test
  image: php:${PHP_VERSION}-cli
  services:
    - mysql:${MYSQL_VERSION}
  before_script:
    - apt-get update -qq && apt-get install -y -qq git mysql-client
    - docker-php-ext-install mysqli pdo pdo_mysql
    - mysql --version
  script:
    - echo "🧪 Running application tests..."
    - php -v
    - mysql -h mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};"
    - mysql -h mysql -u root -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} < database.sql
    - echo "✅ Database setup completed"
    - echo "✅ Tests completed successfully"
  artifacts:
    reports:
      junit: test-results.xml
    paths:
      - test-results/
    expire_in: 1 week
  only:
    - branches
    - merge_requests

database_tests:
  stage: test
  image: php:${PHP_VERSION}-cli
  services:
    - mysql:${MYSQL_VERSION}
  before_script:
    - apt-get update -qq && apt-get install -y -qq mysql-client
    - docker-php-ext-install mysqli
  script:
    - echo "🗄️ Testing database connectivity and schema..."
    - mysql -h mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "SHOW DATABASES;"
    - mysql -h mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE ${MYSQL_DATABASE};"
    - mysql -h mysql -u root -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} < database.sql
    - mysql -h mysql -u root -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} -e "SHOW TABLES;"
    - echo "✅ Database tests completed"
  only:
    - branches
    - merge_requests

# ========================================
# SECURITY STAGE
# ========================================

security_scan:
  stage: security
  image: php:${PHP_VERSION}-cli
  before_script:
    - apt-get update -qq && apt-get install -y -qq git
  script:
    - echo "🔒 Running security scans..."
    - echo "Checking for hardcoded passwords..."
    - grep -r "password.*=" . --include="*.php" | grep -v "password_hash" | grep -v "password_verify" || echo "No hardcoded passwords found"
    - echo "Checking for SQL injection vulnerabilities..."
    - grep -r "mysql_query\|mysqli_query" . --include="*.php" | grep -v "prepare" || echo "Using prepared statements - Good!"
    - echo "✅ Security scan completed"
  allow_failure: true
  only:
    - branches
    - merge_requests

dependency_scan:
  stage: security
  image: php:${PHP_VERSION}-cli
  script:
    - echo "📦 Scanning dependencies for vulnerabilities..."
    - echo "No composer dependencies to scan in this project"
    - echo "✅ Dependency scan completed"
  allow_failure: true
  only:
    - branches
    - merge_requests

# ========================================
# BUILD STAGE
# ========================================

build_application:
  stage: build
  image: php:${PHP_VERSION}-cli
  before_script:
    - apt-get update -qq && apt-get install -y -qq zip git
  script:
    - echo "🏗️ Building application package..."
    - mkdir -p build/
    - zip -r build/codevault-${CI_COMMIT_SHORT_SHA}.zip . -x "*.git*" "build/*" "*.zip" "tests/*" ".gitlab-ci.yml"
    - ls -la build/
    - echo "✅ Build completed successfully"
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  only:
    - main
    - develop
    - tags

# ========================================
# DEPLOYMENT STAGE
# ========================================

deploy_staging:
  stage: deploy
  image: php:${PHP_VERSION}-cli
  environment:
    name: staging
    url: https://staging.codevault.example.com
  before_script:
    - apt-get update -qq && apt-get install -y -qq rsync openssh-client
    - 'which ssh-agent || ( apt-get install -y openssh-client )'
    - eval $(ssh-agent -s)
  script:
    - echo "🚀 Deploying to staging environment..."
    - echo "Deployment would happen here with actual hosting credentials"
    - echo "Files would be uploaded to staging server"
    - echo "Database would be updated with hosting-setup.sql"
    - echo "✅ Staging deployment completed"
  only:
    - develop
  when: manual

deploy_production:
  stage: deploy
  image: php:${PHP_VERSION}-cli
  environment:
    name: production
    url: https://codevault.example.com
  before_script:
    - apt-get update -qq && apt-get install -y -qq rsync openssh-client
  script:
    - echo "🚀 Deploying to production environment..."
    - echo "Production deployment would happen here"
    - echo "This could include:"
    - echo "- Upload files to InfinityFree hosting"
    - echo "- Update database schema"
    - echo "- Clear application cache"
    - echo "- Send deployment notifications"
    - echo "✅ Production deployment completed"
  only:
    - main
    - tags
  when: manual

# ========================================
# MONITORING STAGE
# ========================================

health_check:
  stage: monitor
  image: curlimages/curl:latest
  script:
    - echo "🏥 Running health checks..."
    - echo "Would check application endpoints:"
    - echo "- GET / (homepage)"
    - echo "- GET /login.php"
    - echo "- Database connectivity"
    - echo "✅ Health checks completed"
  only:
    - main
  when: manual

performance_test:
  stage: monitor
  image: php:${PHP_VERSION}-cli
  script:
    - echo "⚡ Running performance tests..."
    - echo "Would test:"
    - echo "- Page load times"
    - echo "- Database query performance"
    - echo "- Memory usage"
    - echo "✅ Performance tests completed"
  only:
    - main
  when: manual

# ========================================
# SCHEDULED JOBS
# ========================================

backup_database:
  stage: monitor
  image: mysql:${MYSQL_VERSION}
  script:
    - echo "💾 Creating database backup..."
    - echo "Database backup would be created and stored"
    - echo "✅ Backup completed"
  only:
    - schedules
  when: manual

# ========================================
# NOTIFICATION TEMPLATES
# ========================================

.notification_template: &notification
  after_script:
    - echo "📢 Sending notifications..."
    - echo "Pipeline status: $CI_PIPELINE_STATUS"
    - echo "Commit: $CI_COMMIT_SHA"
    - echo "Branch: $CI_COMMIT_REF_NAME"

# Apply notifications to important jobs
deploy_production:
  <<: *notification

# ========================================
# RULES AND CONDITIONS
# ========================================

# Only run full pipeline on main/develop branches
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
